/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const priorityDelivery = require('./code/priorityDelivery');

class TableExport extends LCAPApplicationService {
    async init() {

        this.on('priorityDelivery','SrvProjection', async (req) => {

            console.log("action entered\n");
             
            return await priorityDelivery(req,this);
        });

        this.on('Export', async (req) => {

            console.log("EXPORT ACTION ENTERED");
            return "smallstring";
           // return await priorityDelivery(req,this);
        });


        this.on('READ','SrvProjection', async (req,next) => {
      
            console.log("Req: "+req);
            console.log(req);
            console.log('READ event triggered');
            // Custom logic for READ operation
      
            return await next();
          });
      
        return super.init();
    }
}


module.exports = {
    TableExport
};